version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build:
    docker:
      - image: node:14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker
          command: apt-get update && apt-get install -y docker.io
      - run:
          name: Build Docker Image
          command: |
            docker build -t noahbrochu/my-k8s-app:qa .
      - run:
          name: Push Docker Image
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push noahbrochu/my-k8s-app:qa
