apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app
  namespace: dev
  annotations:
      circleci.com/project-id: dd165868-b538-43f2-a275-bde12c28d2e0
  labels:
      circleci.com/component-name: my-k8s-app
      circleci.com/version: 1.0.0
      app: my-k8s-app
spec:
  selector:
    matchLabels:
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: my-k8s-app
        circleci.com/component-name: my-k8s-app
        circleci.com/version: 1.0.0
    spec:
      containers:
      - name: my-k8s-app
        image: NoahBrochu/my-k8s-app:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      restartPolicy: Always